### ISSUE TITLE
content update on Artwork and logos page 

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#16]
Hi,
Please update the following logos on this page: https://www.eclipse.org/org/artwork/
Please also consider same sizing and consistent look within all logos. We want to look at how to balance their representation. 

Logos that need update: 
Jakarta EE Compatible, Jakarta EE Member, Adoptium, Cloud Dev Tools, 
Edge Native, MicroProfile, OpenADx, openMobility,
openPASS, OSGi, Tangle EE, Sparkplug

FYI, the updated logos have TM / R symbol.

[R-TM- logos 2.zip](https://github.com/EclipseFdn/eclipse.org/files/7253142/R-TM-.logos.2.zip)

Thanks for your help,
Mehrnaz

**Comment by meKokabi** [comment]
@SharonCorbett  FYR!

**Comment by linkfang** [comment]
Hi @meKokabi ,

Can you update these logos for me please? 

Missing symbols or logos:
- There is no black and white logo for Jakarta EE Compatible
- JakartaEE_Logo_Member (R)-Bk (black version) doesn't have the "R" symbol 
- ECD tools logo, the "TM" is not fully showed, can only see half of the "M" (see screenshot below)

Remove relatively large blank spaces so that all logos could use similar sizes:
- Jakarta EE Compatible colored logo has a relatively larger blank space around it (compared to other Jakarta logos). 
- IoT logo has a relatively large blank space (top and bottom).
- MicroProfile logo has a relatively large blank space (top and bottom). 

![image](https://user-images.githubusercontent.com/43075439/135680845-9cc04dc0-35ef-47ea-9d5a-c0d8a293da54.png)

Please preview the changes so far and let me know if there is any issues (or need to re-size any logos), thanks!
https://staging.eclipse.org/org/artwork/

**Comment by meKokabi** [comment]
Good Morning @linkfang : Please find attached including the entire logos published on artwork page adjusted formats.
In addition to those that requested above I have added the Gemoc, as it looks relatively large, as well EdgeNative.  
Please let me know If I missed any files.

[Registrate logos.zip](https://github.com/EclipseFdn/eclipse.org/files/7277787/Registrate.logos.zip)

Thanks,
M

**Comment by linkfang** [comment]
Hi @meKokabi ,

I think you might miss Jakarta EE Compatible black and white version?
I can only see colour version. I assume we do need a black and white version?
![image](https://user-images.githubusercontent.com/43075439/135903697-e5b9a17b-0998-4ad5-a384-a9e4b47ba257.png)

**Comment by linkfang** [comment]
And please check the new changes here:
https://staging.eclipse.org/org/artwork/

As the Gemoc logo you offered has a white background color, so I did not use it. Just reduced the size of existing logo.

**Comment by meKokabi** [comment]
Looks fine to me, for more consistency could you please just make Asciidoc
and openmobility a bit smaller. Thanks!
I will share compatible black and whtie files shortly.

**Comment by meKokabi** [comment]
[JakartaCompatibleBlack.zip](https://github.com/EclipseFdn/eclipse.org/files/7280726/JakartaCompatibleBlack.zip)

**Comment by linkfang** [comment]
OK, done!
Width of those 2 logos has been reduced from 330px to 300px.

https://staging.eclipse.org/org/artwork/

**Comment by meKokabi** [comment]
Looks Great! Thanks!

**Comment by linkfang** [comment]
Awesome! No problem!
The changes will be live once code review is done.

**Comment by meKokabi** [comment]
👍

**Comment by linkfang** [comment]
Now the changes are live!

**Comment by linkfang** [comment]
> @linkfang Tangle EE does not have the symbol in the correct place. It needs to be after Tangle not after EE.

Hi @meKokabi , can you update the logo and attach it here? Thanks!

**Comment by meKokabi** [comment]
@linkfang Please find attached including Tangle EE logo.

[Tangle-EE.zip](https://github.com/EclipseFdn/eclipse.org/files/7302803/Tangle-EE.zip)

**Comment by SharonCorbett** [comment]
+1  
Let's push live
