### ISSUE TITLE
update the Eclipse Membership page resources 

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/eclipse.org#2]
Please update the Member prospectus Download button link at:  https://www.eclipse.org/membership/documents/membership-prospectus.pdf with the new Pdf attached here.

[membership-prospectus.pdf](https://github.com/EclipseFdn/eclipse.org/files/5814916/membership-prospectus.pdf)

Thanks!

**Comment by flora8984461** [comment]
Hi @meKokabi 
Please check the preview on staging:
https://staging.eclipse.org/membership/documents/membership-prospectus.pdf

Please help check if the contents updated? I have roughly gone through the two docs, seems no big difference. Please advise which parts are the changes so that I can tell it's updated. Thanks a lot!

**Comment by meKokabi** [comment]
Thank You!  (The difference was just a tiny change on the footer.)
This is ready for moving to publishing.
Thanks!

**Comment by flora8984461** [comment]
The change is live on prod. I'm going to mark this as resolved, please feel free to reopen if more changes needed. Thanks!
